### ISSUE TITLE
jQuery refactoring a bit

### ISSUE THREAD

**Issue by Kaidanov** [lev18d/MineSweeper#3]
mineCraft.blockMover - why do you need this code?
 itemSelectedBox.attr('data', blockSelected.attr('data')); 

blockSelected.attr('class') !== 'sky box'
you can use .not of jquery

 blockSelected.removeClass(blockSelected.attr('class'));
 blockSelected.addClass(mineCraft.blocks['sky'].class);
 blockSelected.addClass('box');
you can use attr to set it in one line, and not 3

**Comment by benjipollock** [comment]
data attribute is to match tools with environment
Added .not
Also changed .attr('class') === blah to hasClass.
Changed to one line using attr in multiple spots
